import Foundation

/// 言語ごとの文言テーブル。新しい言語を追加する場合は `AppLanguage` に case を足し、
/// ここに対応するテーブルを追加するだけでよい。
enum LocalizationStrings {
    static let ja: [LocalizationKey: String] = [
        .commonCancel: "キャンセル",
        .commonSave: "保存",
        .commonDelete: "削除",
        .commonClose: "閉じる",

        .languageSwitchToJapanese: "日本語に切り替え",
        .languageSwitchToEnglish: "英語に切り替え",

        .deviceOffline: "オフライン",
        .deviceUpdating: "更新中…",
        .deviceSearching: "検索中",

        .transferPickerLabel: "転送",
        .transferTabInFlight: "進行",
        .transferTabCompleted: "完了",
        .transferMetaWaitingPermission: "許可待ち",
        .transferMetaConnecting: "接続中",
        .transferMetaSendingPercent: "送信 %d%%",
        .transferMetaReceivingPercent: "受信 %d%%",
        .transferSavedToPhotos: "写真に保存済み",
        .transferSavedToFiles: "ファイルに保存済み",

        .filePickSourceTitle: "選択",
        .filePickPhotoVideo: "写真・動画",
        .filePickFile: "ファイル",
        .filePickDeselect: "選択を解除",
        .filePickWaiting: "待機",
        .filePickPrompt: "画像・ファイルを選択",

        .receiveRequestPendingCount: "+%d 件待ち",
        .receiveRequestDeny: "拒否",
        .receiveRequestAllow: "許可",

        .saveDialogTitle: "保存先を選択",
        .saveDialogSaveToPhotos: "写真アプリに保存",
        .saveDialogSaveToFiles: "ファイルアプリに保存",

        .connectionDebugTitle: "接続状態",
        .connectionDebugSignalingSubtitle: "転送時 / テスト接続",
        .connectionDebugLastError: "直近のエラー: %@",

        .connectionStateDisconnected: "切断",
        .connectionStateConnecting: "接続中",
        .connectionStateConnected: "接続済み",
        .connectionStateReconnecting: "再接続中",

        .contentViewClearHistoryConfirmTitle: "転送済みファイルを消去しますか？",
        .contentViewClearHistoryButton: "消去",
        .contentViewSupportA11y: "サポート",
        .contentViewClearHistoryA11y: "転送済みファイルを消去",

        .errorServerNotConfiguredLAN: "同一 Wi-Fi で PC または Mac の LynkOS（Django）を起動してください。",
        .errorSignalingUnreachable: "シグナリングサーバーに接続できません",
        .errorDeviceListPrefix: "デバイス一覧: %@",
        .errorSendFailedPrefix: "送信失敗: %@",
        .errorReceiveFailedPrefix: "受信失敗: %@",
        .settingsTitle: "設定",
        .settingsIconLabel: "アイコン",
        .settingsPhotoButton: "写真",
        .settingsNameLabel: "名前",
        .settingsDeveloperMode: "デベロッパーモード",
        .settingsSignalingOverrideLabel: "シグナリングサーバー（上書き）",
        .settingsServerPlaceholder: "空欄で LAN 自動検出",
        .settingsServerHint: "通常は同一 Wi-Fi 上の LynkOS を自動検出します。開発・検証時のみ URL を手入力してください。",

        .supportTitle: "サポート",
        .supportLegalSectionTitle: "法務",

        .debugHubSearching: "LAN 上の LynkOS サーバーを探索中…",
        .debugInboxEventsPlaceholder: "Inbox イベントはここに表示されます",
        .deviceNearbyFallbackName: "近くのデバイス",

        .shareLoadingAttachment: "共有内容を読み込み中…",
        .shareSetupRequiredTitle: "セットアップが必要です",
        .shareSetupRequiredSubtitle: "同一 Wi-Fi で PC または Mac の LynkOS を起動してください。初回は LynkOS アプリを一度開いてください。",
        .shareSearchingNearbyDevices: "近くのデバイスを探しています…",
        .shareRejectedTitle: "拒否されました",
        .shareFileFallbackName: "ファイル",
        .shareDeviceListSearching: "検索中…",
        .shareDeviceListEmptyHint: "同一 Wi-Fi 上で Web / iOS の LynkOS が起動している必要があります",
        .shareSendCompletedTitle: "送信完了",
        .shareSendingToPeer: "%@ に送信中…",
        .shareWaitingAcceptFromPeer: "%@ の許可を待っています…",
        .shareConnectingToPeer: "%@ に接続中…",
        .shareAttachmentLoadFailed: "共有内容を読み込めませんでした",
        .shareServerUnreachable: "サーバーに接続できません",
        .shareSharedFileNotFound: "共有ファイルが見つかりません",
        .shareGenericDeviceFallbackName: "デバイス",
        .shareBonjourSearching: "Bonjour: 近くの LynkOS を探索中…",
        .shareBonjourFoundCount: "Bonjour: %d 件",
        .shareNoResponseFromPeer: "%@ からの応答がありませんでした",

        .errorUnknown: "不明",
        .errorServerDisconnected: "サーバーとの接続が切れました",
        .errorPeerDisconnected: "相手が切断しました",
        .errorConnectionLost: "接続が切断されました",
        .errorOfferProcessingFailed: "Offer 処理失敗: %@",
        .errorAnswerProcessingFailed: "Answer 処理失敗: %@",
        .errorOfferCreationFailed: "Offer 作成失敗",
        .errorPeerRejectedTransfer: "相手が転送を拒否しました",
        .errorReceiveFileCreateFailed: "受信ファイルを作成できませんでした",
        .errorReceiveFileSaveFailed: "受信ファイルの保存に失敗しました",

        .toastSelectFileFirst: "先にファイルを選択してください",
        .toastFileLoadFailed: "ファイルを読み込めませんでした",
        .toastSendRequestFailed: "転送リクエストの送信に失敗しました",
        .toastPhotoLoadFailed: "写真を読み込めませんでした",
        .toastImageLoadFailed: "画像を読み込めませんでした",
        .toastImageTooLarge: "画像が大きすぎます",
        .toastReceiveStartFailed: "受信開始に失敗しました",
        .toastRejectSendFailed: "拒否の送信に失敗しました",
        .toastPeerRejected: "相手が拒否しました",
        .toastNoResponse: "相手からの応答がありませんでした",
        .toastNotSavableToPhotos: "このファイルは写真アプリに保存できません",
        .toastPhotoAccessDenied: "写真へのアクセスが許可されていません",
        .toastSaveFailed: "保存に失敗しました",
        .toastSavedToPhotosNamed: "%@ を写真に保存しました",
        .toastFileNotFound: "ファイルが見つかりません",
        .toastSavedNamed: "%@ を保存しました",
        .toastDeviceListRefreshFailedKeepAlive: "一覧の更新に失敗しました。接続は維持されています",
        .toastSentNamed: "%@ を送信しました",
        .toastReceiveFilePrepareFailed: "受信ファイルの準備に失敗しました",
    ]

    static let en: [LocalizationKey: String] = [
        .commonCancel: "Cancel",
        .commonSave: "Save",
        .commonDelete: "Delete",
        .commonClose: "Close",

        .languageSwitchToJapanese: "Switch to Japanese",
        .languageSwitchToEnglish: "Switch to English",

        .deviceOffline: "Offline",
        .deviceUpdating: "Updating…",
        .deviceSearching: "Searching",

        .transferPickerLabel: "Transfer",
        .transferTabInFlight: "In progress",
        .transferTabCompleted: "Completed",
        .transferMetaWaitingPermission: "Waiting for approval",
        .transferMetaConnecting: "Connecting",
        .transferMetaSendingPercent: "Sending %d%%",
        .transferMetaReceivingPercent: "Receiving %d%%",
        .transferSavedToPhotos: "Saved to Photos",
        .transferSavedToFiles: "Saved to Files",

        .filePickSourceTitle: "Select",
        .filePickPhotoVideo: "Photo/Video",
        .filePickFile: "File",
        .filePickDeselect: "Deselect",
        .filePickWaiting: "Waiting",
        .filePickPrompt: "Select a photo or file",

        .receiveRequestPendingCount: "+%d more waiting",
        .receiveRequestDeny: "Deny",
        .receiveRequestAllow: "Allow",

        .saveDialogTitle: "Choose where to save",
        .saveDialogSaveToPhotos: "Save to Photos",
        .saveDialogSaveToFiles: "Save to Files",

        .connectionDebugTitle: "Connection status",
        .connectionDebugSignalingSubtitle: "During transfer / test connection",
        .connectionDebugLastError: "Last error: %@",

        .connectionStateDisconnected: "Disconnected",
        .connectionStateConnecting: "Connecting",
        .connectionStateConnected: "Connected",
        .connectionStateReconnecting: "Reconnecting",

        .contentViewClearHistoryConfirmTitle: "Clear transferred files?",
        .contentViewClearHistoryButton: "Clear",
        .contentViewSupportA11y: "Support",
        .contentViewClearHistoryA11y: "Clear transferred files",

        .errorServerNotConfiguredLAN: "Start LynkOS (Django) on a PC or Mac on the same Wi-Fi network.",
        .errorSignalingUnreachable: "Can't connect to the signaling server",
        .errorDeviceListPrefix: "Device list: %@",
        .errorSendFailedPrefix: "Send failed: %@",
        .errorReceiveFailedPrefix: "Receive failed: %@",
        .settingsTitle: "Settings",
        .settingsIconLabel: "Icon",
        .settingsPhotoButton: "Photo",
        .settingsNameLabel: "Name",
        .settingsDeveloperMode: "Developer Mode",
        .settingsSignalingOverrideLabel: "Signaling Server (Override)",
        .settingsServerPlaceholder: "Leave blank to auto-detect on LAN",
        .settingsServerHint: "LynkOS on the same Wi-Fi network is normally detected automatically. Only enter a URL manually for development or testing.",

        .supportTitle: "Support",
        .supportLegalSectionTitle: "Legal",

        .debugHubSearching: "Searching for a LynkOS server on the LAN…",
        .debugInboxEventsPlaceholder: "Inbox events will appear here",
        .deviceNearbyFallbackName: "Nearby device",

        .shareLoadingAttachment: "Loading shared content…",
        .shareSetupRequiredTitle: "Setup required",
        .shareSetupRequiredSubtitle: "Start LynkOS on a PC or Mac on the same Wi-Fi network. Open the LynkOS app once first if this is your first time.",
        .shareSearchingNearbyDevices: "Looking for nearby devices…",
        .shareRejectedTitle: "Declined",
        .shareFileFallbackName: "File",
        .shareDeviceListSearching: "Searching…",
        .shareDeviceListEmptyHint: "LynkOS must be running on the Web or iOS on the same Wi-Fi network",
        .shareSendCompletedTitle: "Sent",
        .shareSendingToPeer: "Sending to %@…",
        .shareWaitingAcceptFromPeer: "Waiting for %@ to accept…",
        .shareConnectingToPeer: "Connecting to %@…",
        .shareAttachmentLoadFailed: "Couldn't load the shared content",
        .shareServerUnreachable: "Can't connect to the server",
        .shareSharedFileNotFound: "The shared file can't be found",
        .shareGenericDeviceFallbackName: "Device",
        .shareBonjourSearching: "Bonjour: Searching for nearby LynkOS…",
        .shareBonjourFoundCount: "Bonjour: %d found",
        .shareNoResponseFromPeer: "No response from %@",

        .errorUnknown: "Unknown",
        .errorServerDisconnected: "Connection to the server was lost",
        .errorPeerDisconnected: "The other device disconnected",
        .errorConnectionLost: "The connection was lost",
        .errorOfferProcessingFailed: "Failed to process the offer: %@",
        .errorAnswerProcessingFailed: "Failed to process the answer: %@",
        .errorOfferCreationFailed: "Failed to create the offer",
        .errorPeerRejectedTransfer: "The other device declined the transfer",
        .errorReceiveFileCreateFailed: "Failed to create the incoming file",
        .errorReceiveFileSaveFailed: "Failed to save the incoming file",

        .toastSelectFileFirst: "Select a file first",
        .toastFileLoadFailed: "Couldn't load the file",
        .toastSendRequestFailed: "Failed to send the transfer request",
        .toastPhotoLoadFailed: "Couldn't load the photo",
        .toastImageLoadFailed: "Couldn't load the image",
        .toastImageTooLarge: "The image is too large",
        .toastReceiveStartFailed: "Failed to start receiving",
        .toastRejectSendFailed: "Failed to send the decline",
        .toastPeerRejected: "The recipient declined",
        .toastNoResponse: "No response from the recipient",
        .toastNotSavableToPhotos: "This file can't be saved to Photos",
        .toastPhotoAccessDenied: "Photo library access isn't allowed",
        .toastSaveFailed: "Failed to save",
        .toastSavedToPhotosNamed: "Saved %@ to Photos",
        .toastFileNotFound: "File not found",
        .toastSavedNamed: "Saved %@",
        .toastDeviceListRefreshFailedKeepAlive: "Failed to refresh the device list. The connection is still active.",
        .toastSentNamed: "Sent %@",
        .toastReceiveFilePrepareFailed: "Failed to prepare the received file",
    ]
}
